---
# ****************************** Security group ******************************
# Create a TCP rule covering all ports
security_groups:
  - name: instance1-security-group
    description: "security group for instance1 server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: instance2-security-group
    description: "security group for instance2 server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: instance3-security-group
    description: "security group for instance3 server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: instance4-security-group
    description: "security group for instance4 server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# ****************************** Volume ******************************
volumes:
  - vol_name: instance1-volume
    vol_size: 135
    device: /dev/vdb
    mountpoint: /home/ubuntu/data
  - vol_name: instance2-volume
    vol_size: 135
    device: /dev/vdb
    mountpoint: /home/ubuntu/data
  - vol_name: instance3-volume
    vol_size: 135
    device: /dev/vdb
    mountpoint: /home/ubuntu/data


# ****************************** Instance ******************************
instances:
  - name: instance1
    volume_ids: "{ instance1_volumes|default([]) }"
    volumes: ["instance1-volume"]
  - name: instance2
    volume_ids: "{ instance2_volumes|default([]) }"
    volumes: ["instance2-volume"]
  - name: instance3
    volume_ids: "{ instance3_volumes|default([]) }"
    volumes: ["instance3-volume"]

