---
# tasks file for common
# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

- name: install pip3
  become: yes
  apt: name=python3-pip state=present 


- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk==0.61']
    state: latest
# pip install openstacksdk