---
- hosts: database
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb

- hosts: masternode
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb-cluster
   
  
  
