version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=Test!123
      - COUCHDB_BIND_ADDRESS=0.0.0.0
    volumes:
      - ./dbdata:/opt/couchdb/data
