---

- name: Gather facts of remote host
  setup:
    gather_subset: all
    
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip


- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: sudo apt-get install ['git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'vim', 'python3-pip', 'libblacs-mpi-dev', 'python3-venv','openmpi-bin']
  tags: always
  become: yes
  apt:
    name: ['git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'vim',  'python3-venv','openmpi-bin']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install dockerpy
  become: yes
  apt:
    name: ['docker']
    update_cache: yes
    state: latest

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install docker-ce
  become: yes
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  become: yes
  pip:
    name: docker

 